---
tags:
- metaprogramacion
- objetos
- basico
- inspeccion
- instance_methods
layout: input_right
editor: code
type: problem
extra_visible: false
language: 
teacher_info: 
manual_evaluation: false
choices: []
